### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by Ironholds** [forwards/Community#1]
I'm seeing a coupla surveys here but I don't know what the repo is about from the title/README.

**Comment by julierennes** [comment]
Olivier,

I feel so bad not to have done anything yet... I have difficulties to 
hnadle my new poistion with the new 10 hours/ week lecture!

Anyway, no excuse,  do you want me to have a look at something in 
particular in the survey or should I just use some exploratory methods I 
have in mind to get insight into the association between variables 
(multiple correspondance analaysis)

Best,

JJ
